### ISSUE TITLE
Opcodes

### ISSUE THREAD

**Issue by FluffyPanda77** [TerableCoder/TerableAngler#1]
do you have op codes for sea? 
running into some errors
![unknown](https://user-images.githubusercontent.com/46365382/52278864-0dcd4b00-2993-11e9-8da1-af3728ad73e2.png)

**Comment by TerableCoder** [comment]
I don't

**Comment by feixiang-1** [comment]
we need TW region op codes

**Comment by TerableCoder** [comment]
no

**Comment by feixiang-1** [comment]
how to find op codes?  or have teaching video?

**Comment by TerableCoder** [comment]
use https://github.com/SoliaRdi/PacketsLogger
and/or https://github.com/Owyn/alex-packet-id-finder
You'll have to learn how to use them yourself though.

**Comment by TerableCoder** [comment]
TW opcodes https://github.com/zc149352394/Terable-Angler

**Comment by TerableCoder** [comment]
TW opcodes added
