### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by wujorogal** [TerableCoder/TerableAngler#2]
![obraz](https://user-images.githubusercontent.com/46306175/54866099-43c26500-4d70-11e9-9b46-d343bfad5811.png)

thats basicly what happends for me when i try to start the mod

EU server btw

**Comment by TerableCoder** [comment]
You're missing the EU opcodes for some packets. I only have the NA ones. You'll have to find people who do have them for EU, or use https://github.com/SoliaRdi/PacketsLogger
and/or https://github.com/Owyn/alex-packet-id-finder
to find them. You'll have to learn how to use them yourself though.

**Comment by TerableCoder** [comment]
some EU opcodes here in protocol.344301.map https://github.com/SoliaRdi/sell-angler-tokens

**Comment by TerableCoder** [comment]
EU Opcodes added
