### ISSUE TITLE
doing my own eu mapping. stuck at C_STORE_SELL_ADD_BASKET

### ISSUE THREAD

**Issue by trev44** [TerableCoder/TerableAngler#3]
these are right?

C_MEDAL_STORE_BUY_ADD_BASKET
C_MEDAL_STORE_COMMIT 
C_STORE_SELL_ADD_BASKET
C_STORE_COMMIT
S_MEDAL_STORE_BASKET

i have manually done all the opcodes for these.

i talk to the vendor and it auto buys x80 crate 1 designs then when
i talk to the merchant, it closes straight away.

any ideas please help.

**Comment by TerableCoder** [comment]
From protocol.344301.map: (should match yours)
C_STORE_SELL_ADD_BASKET = 28603
C_STORE_COMMIT = 22193
C_MEDAL_STORE_BUY_ADD_BASKET = 25790
C_MEDAL_STORE_COMMIT = 45061


Make sure that you:
Put the "C_STORE_COMMIT.1.def" file into your tera-proxy\node_modules\tera-data\protocol\ folder.
Put the protocol files into your tera-proxy\node_modules\tera-data\map\ folder.
Opcodes Known for: NA, EU, RU, TW, SEA

**Comment by TerableCoder** [comment]
EU opcodes added https://github.com/TerableCoder/TerableAngler/blob/master/map/protocol.345887.map
