### ISSUE TITLE
EU- auto 80 crates but no npc sell?

### ISSUE THREAD

**Issue by trev44** [TerableCoder/TerableAngler#5]
it auto deposits 80 crates in basket and buys them 
but
no action on npc to sell? (fish supply highwatch next to angler vendor or only monti?)

opcodes are fine (EU)

also i keep getting this for terableangler specifically. please help

**Comment by trev44** [comment]
![Capture](https://user-images.githubusercontent.com/48329651/55420436-552d1d80-5577-11e9-9fc4-c6ba338e6062.PNG)

**Comment by TerableCoder** [comment]
I updated it, tell me if it works now. I don't have an EU account and NA is on patch 79 still.

**Comment by trev44** [comment]
i sold my crates matually so tomorrow once i get more tokens. if thats ok, ill let you know

**Comment by trev44** [comment]
i just tried it now. thanks a lot. its working :)
may i ask what is this proxy error caused from, it happens with a few other mods too.
just so i can tell other owners of the mods.

**Comment by TerableCoder** [comment]
nice

**Comment by ghost** [comment]
I'm also getting this issue with monti.
EU.

**Comment by ghost** [comment]
Yeah, doesn't sell, but does buy.
Something seems to be skipping a step in the mod, I've made sure I'm doing it right.
Need help, @TerableCoder

**Comment by ghost** [comment]
Okay, from step to step:
If nothing open: Nothing.
If angler open: Buys fish crates, reopens angler, does not sell to merchant.
If merchant open: Closes merchant and then does nothing.
I've made sure to designate the NPCs properly.

**Comment by ghost** [comment]
Before you ask, I have properly installed the maps and protocols.

**Comment by ghost** [comment]
I think it may be trying to sell too fast, then goes to the next step without confirming the last.

**Comment by ghost** [comment]
I should also mention the loop is still running, if you talk to the angler token vendor (at least after a second time) it will auto-buy, but the rest of the loop doesn't function correctly, this is repeatable.

**Comment by TerableCoder** [comment]
I just tested it and it still works. It sounds to me like you aren't talking to both npcs properly,
Type "teraa", click on Angler Token Vendor, click the green Angler Token Shop button, close the window, click on the merchant, click the green Buy General Goods, close the window, type "teraa start".

**Comment by ghost** [comment]
I have done this 3 times to confirm, and it is still not working.
The first time it opened up my inventory but nothing else, the other two times nothing happened.

**Comment by ghost** [comment]
For more information: I am playing from NA on the EU server, could ping factor into this?

**Comment by TerableCoder** [comment]
Possibly, I added configurable delay to the module

**Comment by ghost** [comment]
Still no dice unfortunately, I tried several times, eventually with ridiculous timings like 3000ms for everything.
Is there anymore information I can give you that may help?

**Comment by ghost** [comment]
(this is with the new update you just did)

**Comment by TerableCoder** [comment]
Put the "C_STORE_COMMIT.1.def" file into your tera-proxy\node_modules\tera-data\protocol\ folder.
Put the protocol files into your tera-proxy\node_modules\tera-data\map\ folder.

record a video of you using the module so I can see it

**Comment by ghost** [comment]
Sorry for the wait, I had to relearn some video editing stuff.
I've replaced those files several times already, don't worry.
I've tried several variations of this, such as keeping the inventory open, and using a traveling merchant scroll.
Anyway, here's the [redacted].

**Comment by ghost** [comment]
Tell me when you download the video so I can delete, or edit my post please.

**Comment by TerableCoder** [comment]
I've seen the video now, I'd guess that you overwrote the map_base protocol file that contains opcodes like C_NPC_CONTACT. You can redownload proxy or download it from https://github.com/TerableCoder/map_base. It goes into the folder Proxy\node_modules\tera-data\map_base.

**Comment by TerableCoder** [comment]
Also, are you getting any errors on your proxy window? Screenshot them if so.

**Comment by ghost** [comment]
I replaced the map_base file just in case, but unfortunately still no dice.
No proxy errors either, unfortunately.
I'll go ahead and just reinstall everything just in case, but I don't think it's user error in this case.

**Comment by ghost** [comment]
Reinstalled everything, still not working.
Same problem as before.

**Comment by ghost** [comment]
Could one or more of the EU codes perhaps be incorrect?

**Comment by TerableCoder** [comment]
The protocol.344895.map opcodes are all about adding item to the basket and clicking confirm. You're having problems with talking to the NPC, so the opcodes wouldn't be an issue. I don't know why yours doesn't work.

**Comment by ghost** [comment]
Well I'm not entirely sure whether adding items to the basket and clicking confirm works or not, I never got it to that part of the loop no matter what I did.
The problem is that it doesn't open up the angler token vendor and buy the fish crates, it only opens my inventory, and then stalls there.

**Comment by ghost** [comment]
Ah my bad, I misread your comment.

**Comment by ghost** [comment]
Can you confirm this works for anyone on the EU server?

**Comment by TerableCoder** [comment]
The creator of this issue and the creator of another issue had it working on EU before. Did you have this module working before and now it doesn't work? Or have you never had it working?

**Comment by ghost** [comment]
I installed it yesterday, and it has never worked.
I have fiddled with a lot of stuff after several failures using it normally, but to no avail.

**Comment by ghost** [comment]
Oh, it could be the PUBG update that caused this.
The codes may really be incorrect, as let-me-fish had to update too IIRC.

**Comment by TerableCoder** [comment]
It updated to protocol.344895.map, the same one I updated to. This seems to be an issue with your specific proxy installation. Idk if you're not using Caali proxy or what the issue is with your proxy, but I have no way to help you beyond this.

**Comment by ghost** [comment]
I see, that's unfortunate.
I am using Caali proxy, and even after a fresh install still nothing...
Everything else works, it's just this mod, I've done all the steps right, multiple times, so I shouldn't be failing.
Perhaps a(n open) issue should be made to see if there are other people, from the EU server, having this problem also?

**Comment by ghost** [comment]
Okay, found the culprit.
There's some sort of incompatibility with [item-cache](https://github.com/tera-mods/item-cache).
Removing it solved the problem, however do you have any ideas on a more graceful fix?

**Comment by TerableCoder** [comment]
No. I have item-cache removed because of fishing modules, so I forgot it existed. Item-cache makes your inventory not update, so this module thinks your inventory is empty. The only way to fix this is to remove it.

**Comment by ghost** [comment]
I see. Might want to put a warning in the readme then.
Thanks for all the help.
