### ISSUE TITLE
Needs update for patch 81.

### ISSUE THREAD

**Issue by ghost** [TerableCoder/TerableAngler#6]
Bunch of javascript errors, seems like some codes changed.
Also the buy/sell areas seem to be bigger now.

**Comment by TerableCoder** [comment]
Screenshot the errors please. I don't have an account in a patch 81 region.

**Comment by ghost** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/30435868/56930439-4bc5a100-6aa2-11e9-82e2-95833b051320.png)
![Screenshot_2](https://user-images.githubusercontent.com/30435868/56930440-4bc5a100-6aa2-11e9-9339-b0b8bca9e0a4.png)

**Comment by TerableCoder** [comment]
Added EU/RU/SEA opcodes. They go into the tera-proxy\node_modules\tera-data\map\ folder.
protocol.347373.map
protocol.347375.map
protocol.347377.map

**Comment by ghost** [comment]
It works, thanks!
You might wanna know that patch 81 lets you have 18 spots to buy/sell, so best update the script for that too!

**Comment by TerableCoder** [comment]
Nice, I'll do that once the patch comes to NA.
