### ISSUE TITLE
Could you please tellme how can I fix this 

### ISSUE THREAD

**Issue by vashellsing** [TerableCoder/TerableAngler#9]
Hello im trying to install and use this mod for first time, but when i try to uste it this happend 

![error](https://user-images.githubusercontent.com/34943631/68715637-7378e400-0570-11ea-8599-85048fe7a1d5.PNG)

And i really dont know what to do... Ty

**Comment by TerableCoder** [comment]
fixed. restart proxy and tera

**Comment by vashellsing** [comment]
Sorry, its me again... this happened when i did  "teraa" command 

![Captura](https://user-images.githubusercontent.com/34943631/68716262-d323bf00-0571-11ea-84dd-21619bb63987.PNG)

should i do something?

**Comment by TerableCoder** [comment]
caali updated the definition files again zz

**Comment by TerableCoder** [comment]
fixed

**Comment by vashellsing** [comment]
Ehmm im sorry 



When i use teera , appear the same error..  (but in game says is enable and i need to talk with angler token vendor.. and then summoned merchant... ) so i didit 

![Captura](https://user-images.githubusercontent.com/34943631/68716943-6e696400-0573-11ea-8ee1-889fa33567e5.PNG) 

But all this happened.. @.@

**Comment by TerableCoder** [comment]
it should work regardless of the error, but I fixed it anyways

**Comment by vashellsing** [comment]
Oh i works... The problem now.. is.. im out of angler tokens..  780 ... how many tokens should i need for selling ? ... 

And thank u so much!!

**Comment by TerableCoder** [comment]
900, but it's better to get multiple stacks of angler tokens so that you can afk for a long time while it sells for you

**Comment by vashellsing** [comment]
Thank u so much.... And i really sorry for disturb u >.<

**Comment by vashellsing** [comment]
Well, hi, sorry.... Its me again, now when i tried to sell for first time... appeared this 

![Captura](https://user-images.githubusercontent.com/34943631/68720315-d3758780-057c-11ea-92f2-20d5e88fea1b.PNG)
 
and then...

![Captura2](https://user-images.githubusercontent.com/34943631/68720339-dec8b300-057c-11ea-956b-1d8f38ea53ff.PNG)

did i do something wrong?...

**Comment by TerableCoder** [comment]
you didn't get the opcodes from https://github.com/TerableCoder/TerableOpcodes
Make sure to drop files in the \map\ folder into your proxy's \node_modules\tera-data\map\ folder

**Comment by vashellsing** [comment]
ohh i see... Yes works now!!!... ty so much!! :D
